language: java

jdk:
  - oraclejdk7

script: mvn verify -Dmaven.test.redirectTestOutputToFile=false -B -e -V

install: true

sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    # for analysis
    - $HOME/.sonar

