language: java
jdk:
- oraclejdk8
script: "./travis.sh"
install: true
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar"
before_deploy:
- export RELEASE_JAR=$(ls target/sonar-auth-googleoauth-plugin-*.jar)
- echo "Deploying ${RELEASE_JAR} to GitHub"
- git show -s --pretty=format:"%h - %<|(35)%ai - %an - %s" $(git rev-list --tags --max-count=1)...$(git show | grep "^commit" | awk '{print $2}') | tee target/RELEASE_NOTES
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "${GITHUB_TOKEN}"
  file:
   - "${RELEASE_JAR}"
   - "target/RELEASE_NOTES"
  on:
    repo: InfoSec812/sonar-auth-google
